name: "Setup JS"
description: "Setup Node.js environment and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v5
      with:
        node-version: "22"
        cache: "npm"
    - run: npm ci
      shell: bash
